platform :ios, '12.0'

target 'Example-iOSForPod' do
  use_frameworks!
  project 'Example-iOSForPod'

  # Pods for GTMAppAuth development
  pod 'GTMAppAuth', :path => '../../', :testspecs => ['unit', 'objc-api-integration']

  # In production, you would use:
  # pod 'GTMAppAuth'

  pod 'AppAuth', :git => 'https://github.com/brnnmrls/AppAuth-iOS.git'
  pod 'GTMSessionFetcher/Core', '>= 3.3', '< 4.0'
end
